import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { HeaderBanner, DiscountProvider } from '../components';
import './globals.css';

const montserrat = Montserrat({
	subsets: ['latin'],
	weight: ['400', '500', '600', '700'],
	display: 'swap',
	variable: '--font-montserrat',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ru">
			<body className={`${montserrat.variable} antialiased`}>
				<DiscountProvider>
					<HeaderBanner />
					<div className="pt-26 max-[321px]:pt-[96px]">{children}</div>
				</DiscountProvider>
			</body>
		</html>
	);
}
